healing/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("doctors/", include("doctors.urls")),
    path("patients/", include("patients.urls")),
]

patients/urls.py
from django.urls import path

from patients.views import (
    appointments,
    consulta,
    home,
    new_schedule_appointment,
    schedule_appointment,
)

app_name = "patients"

urlpatterns = [
    path("home/", home, name="home"),
    path(
        "schedule_appointment/<int:doctor_id>/",
        schedule_appointment,
        name="schedule_appointment",
    ),
    path(
        "schedule_appointment/new/<int:appointment_id>/",
        new_schedule_appointment,
        name="new_schedule_appointment",
    ),
    path(
        "schedule_appointment/",
        appointments,
        name="appointments",
    ),
    path(
        "consulta/<int:appointment_id>/",
        consulta,
        name="consulta",
    ),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("logout/", views.logout, name="logout"),
    path("login/", views.login, name="login"),
    path("create/", views.create, name="create"),
]

patients/models.py
from django.contrib.auth.models import User
from django.db import models

from doctors.models import Appointments


class PatientAppointment(models.Model):
    status_choices = (
        ("A", "Agendada"),
        ("F", "Finalizada"),
        ("C", "Cancelada"),
        ("I", "Iniciada"),
    )

    patient = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    date = models.ForeignKey(Appointments, on_delete=models.DO_NOTHING)
    status = models.CharField(max_length=1, choices=status_choices, default="A")
    link = models.URLField(null=True, blank=True)

    def __str__(self):
        return str(self.user.username)

    class Meta:
        verbose_name = "Paciente - Consulta"
        verbose_name_plural = "Paciente - Consultas"

patients/views.py
import datetime

from django.contrib.messages import add_message, constants
from django.http import HttpResponse
from django.shortcuts import redirect, render

from doctors.models import Appointments, Doctor, Specialties
from patients.models import PatientAppointment


def home(request):
    if request.method == "GET":
        doctor_filter = request.GET.get("doctor_filter")
        specialties_filter = request.GET.getlist("specialties_filter")

        doctors = Doctor.objects.all()

        if doctor_filter:
            doctors = doctors.filter(name__icontains=doctor_filter)

        if specialties_filter:
            doctors = doctors.filter(specialty_id__in=specialties_filter)

        specialties = Specialties.objects.all()
        return render(
            request, "home.html", {"doctors": doctors, "specialties": specialties}
        )


def schedule_appointment(request, doctor_id):
    if request.method == "GET":
        doctor = Doctor.objects.get(id=doctor_id)
        appointments = Appointments.objects.filter(
            user=doctor.user, date__gte=datetime.datetime.now(), has_patient=False
        )
        return render(
            request,
            "schedule_appointment.html",
            {"doctor": doctor, "appointments": appointments},
        )


def new_schedule_appointment(request, appointment_id):
    if request.method == "GET":
        appointment = Appointments.objects.get(id=appointment_id)

        patient_appointment = PatientAppointment(
            patient=request.user, date=appointment, status="A"
        )

        patient_appointment.save()
        appointment.has_patient = True
        appointment.save()

        add_message(request, constants.SUCCESS, "Horário agendado com sucesso.")
        return redirect("patients:home")


def appointments(request):
    if request.method == "GET":
        # TODO: add filters

        appointments = PatientAppointment.objects.filter(
            patient=request.user, date__date__gte=datetime.datetime.now()
        )
        return render(
            request, "patient_appointments.html", {"appointments": appointments}
        )


def consulta(request, appointment_id):
    if request.method == "GET":
        appointment = PatientAppointment.objects.get(id=appointment_id)
        doctor = Doctor.objects.get(user=appointment.date.user)
        is_medico = Doctor.objects.filter(user=request.user).exists()
        return render(
            request,
            "patient_consulta.html",
            {"appointment": appointment, "doctor": doctor, "is_medico": is_medico},
        )

patients/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'css/appointments.css' %}">
    <link rel="stylesheet" href="{% static 'css/users.css' %}">
    <link rel="stylesheet" href="{% static 'css/doctors.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
{% endblock 'head' %}


{% block 'body' %}
{% include "navbar.html" %}
<br><br>

<div class="container">
    <div class="row">
        <div class="col-md-8">

            <p style="font-size: 25px" class="p-bold">Olá, <span class="color-dark">{{request.user.username}}.</span></p>
            <form action="{% url 'patients:home' %}" post="GET">
                <input type="text" class="form-control shadow-main-color" placeholder="Busque por profissionais ..." name="doctor_filter">
                <br>
                <div class="especialidades">
                    {% for specialtie in specialties %}
                        <input type="checkbox" name="specialties_filter" value="{{specialtie.id}}">
                        <span class="badge bg-secondary">
                            {{specialtie}}
                        </span>
                    {% endfor %}
                </div>
                <br>
                <input type="submit" value="filtrar" class="btn btn-success btn-dark-color">
            </form>
            <hr>

            <div class="list-medicos">
                {% for doctor in doctors %}
                    <div class="card-medicos shadow-main-color">
                        <div class="row">
                            <div class="col-md-3"><img src="/doctors{{doctor.photo.url}}" class="foto-perfil-card" alt=""></div>
                            <div class="col-md">
                                <p style="font-size: 20px" class="p-bold">{{doctor.name}} <i class="bi bi-patch-check-fill icon-main"></i></p>
                                <p>{{doctor.description}}</p>
                            </div>
                        </div>  
                        <p><i class="bi bi-map icon-main"></i>&nbsp&nbsp{{doctor.street}},{{doctor.street_number}} - {{doctor.neighborhood}}</p>
                        <p><i class="bi bi-calendar2-week icon-main"></i>&nbsp&nbspProxima data: 
                            {% if doctor.next_open_date %}
                                {{doctor.next_open_date}}
                            {% else %}
                                Sem data disponível.
                            {% endif %}
                        </p>
                        <a href="{% url 'patients:schedule_appointment' doctor.id %}" class="btn btn-success btn-dark-color">Agendar</a>
                    </div>
                    <br>
                {% endfor %}
            </div>

        </div>
        <div class="col-md-4">
            <p style="font-size: 25px" class="p-bold">Lembretes</p>

            <p class="bg-main-lembrete">
                <span class="p-bold"><i class="bi bi-exclamation-triangle-fill icon-differential"></i>&nbsp&nbsp Consulta com Pedro Sampario em 7 dias.</span>
            </p>


            
        </div>
    </div>
</div>

{% endblock 'body' %}

patients/templates/patient_appointments.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}

    <link rel="stylesheet" href="{% static 'css/appointments.css' %}">
    <link rel="stylesheet" href="{% static 'css/users.css' %}">
    <link rel="stylesheet" href="{% static 'css/doctors.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

{% endblock 'head' %}

{% block 'body' %}

{% include "navbar.html" %}
    <div class="container">
        <br>
        <h2><span class="color-dark">Suas consultas</span></h2>

        <div class="row">

            <div class="col-md">
                <input type="text" name="especialidades" id="" class="form-control shadow-main-color" placeholder="Especialidades médias">
            </div>
            <div class="col-md">
                <input type="date" name="data" id="" class="form-control shadow-main-color" placeholder="Data da consulta">

            </div>
            <div class="col-md">
                <input type="submit" value="Filtrar" class="btn btn-dark-color-outline">
            </div>
        </div>

        <br>

        <div class="list-minhas-consultas">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Médico</th>
                    <th scope="col">Status</th>
                    <th scope="col">Data</th>
                  </tr>
                </thead>
                <tbody>
                    {% for appointment in appointments  %}
                        <tr>
                            <td><a href="{% url 'patients:consulta' appointment.id %}">Dr(a). {{appointment.date.user.username}}</a></td>
                            <td>{{appointment.get_status_display}}</td>
                            <td>{{appointment.date.user}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>

        </div>


    </div>

{% endblock 'body' %}

patients/templates/patient_consulta.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}

    <link rel="stylesheet" href="{% static 'css/appointments.css' %}">
    <link rel="stylesheet" href="{% static 'css/users.css' %}">
    <link rel="stylesheet" href="{% static 'css/doctors.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

{% endblock 'head' %}

{% block 'body' %}
    {% include "navbar.html" %}

    <br><br>
    <div class="container">
        {% if appointment.status == 'C' %}
            <div class="alert alert-danger" role="alert">
                 Consulta cancelada
            </div>
        {% elif appointment.status == 'F' %}
            <div class="alert alert-success" role="alert">
                Consulta Finalizada
            </div>
        {% elif appointment.status == 'I' %}
            <div class="alert alert-primary" role="alert">
                Consulta inicializada, acesse o link imediatamente!
            </div>
        {% endif %}
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-3"><img src="/doctors{{doctor.photo.url}}" class="foto-perfil-card-lg" alt=""></div>
                    <div class="col-md">
                        <p style="font-size: 20px" class="p-bold">Dr(a). {{doctor.name}} <i class="bi bi-patch-check-fill icon-main"></i></p>
                        <p>{{doctor.description}}</p>
                        <p class="p-bold">{{appointment.date.date}}</p>

                        
                    </div>
                </div> 
                <hr>
                <br>
                <div class="row">
                    <div class="col-md">
                        
                        <p><i class="color-dark bi bi-check-circle-fill"></i> Consulta agendada</p>
                    </div>
                    <div class="col-md">
                        <p><i class="{% if appointment.status == 'F' %}color-dark{% endif %} bi bi-check-circle-fill"></i> Consulta realizada</p>
                    </div>
                    <div class="col-md">
                        <p><i class="bi bi-check-circle-fill"></i> Consulta Avaliada</p>
                    </div>
                </div>
                <hr>
                <h3 class="p-bold">Detalhes da consulta</h3>
                <p style="font-size:20px"><i class="bi bi-calendar3 color-dark"></i>&nbsp {{appointment.date.date}}</p>
                <p style="font-size:20px"><i class="bi bi-tag-fill color-dark"></i></i>&nbsp R$ {{doctor.appointment_price}}</p>
                <a style="cursor: auto;" class="btn btn-dark-color-outline btn-lg">Adicione em seu calendário!</a>
                <hr>
                <h3 class="p-bold">Como acessar ?</h3>
                <p>No horário da consulta acesse o link disponível abaixo</p>
                
                {% if appointment.status == 'I' and consulta.link %}
                    <a href="{{appointment.link}}"  class="btn btn-success btn-dark-color btn-lg" >Acessar consulta</a>
                {% else %}
                    <a href="#"  class="btn btn-success btn-dark-color btn-lg disabled" >Acessar consulta</a>
                {% endif %}
                <hr>
                <h3 class="p-bold">Meus documentos</h3>
                <br>
    
                <br>
                <br>
                <br>
                <br>
            </div>
            <div class="col-md"></div>
        </div>
        
    </div>

{% endblock 'body' %}

patients/templates/schedule_appointment.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}

    <link rel="stylesheet" href="{% static 'css/appointments.css' %}">
    <link rel="stylesheet" href="{% static 'css/users.css' %}">
    <link rel="stylesheet" href="{% static 'css/doctors.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

{% endblock 'head' %}


{% block 'body' %}

{% include "navbar.html" %}
    <div class="container">
        <br><br>

        <div class="row">
            <div class="col-md-8">

                <div class="row">
                    <div class="col-md-3"><img src="/doctors{{doctor.photo.url}}" class="foto-perfil-card" alt=""></div>
                    <div class="col-md">
                        <p style="font-size: 20px" class="p-bold">Dr(a).  {{doctor.name}}<i class="bi bi-patch-check-fill icon-main"></i></p>
                        <p>{{doctor.description}}</p>
                    </div>
                </div> 
                <br>
                {% if messages %}
                    <br>
                    {% for message in messages %}
                        <section class="alert {{message.tags}}">
                            {{message}}
                        </section>
                    {% endfor %}
                {% endif %}
                
                <hr>
            
                <div class="row">
                    {% for appointment in appointments %}
                    <div class="col-md-3">
                      <a class="link" href="{% url 'patients:new_schedule_appointment' appointment.id %}">
                        <div class='selecionar-dia'>
                          <div class="header-dias">
                            <span class="mes">
                              {{appointment.date.month}}
                            </span>
                            
                            <span class="dia-semana">
                              {{appointment.date.weekday}}
                            </span>
                          </div>
                  
                          <div class="conteudo-data">
                            {{appointment.date}}
                          </div>
                        </div>
                      </a>
                      <br>
                    </div>
                  {% endfor %}
                   
                    
                </div>

            </div>
            <div class="col-md-4">

            </div>
        </div>

    </div>
{% endblock 'body' %}