doctors/urls.py
from django.conf.urls.static import static
from django.urls import path

from doctors.views import create, create_appointment, doctor_appointments
from healing import settings

app_name = "doctors"

urlpatterns = [
    path("create/", create, name="create"),
    path("appointments/", create_appointment, name="appointments"),
    path(
        "appointments/all",
        doctor_appointments,
        name="appointments_all",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

healing/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("doctors/", include("doctors.urls")),
    path("patients/", include("patients.urls")),
]

patients/urls.py
from django.urls import path

from patients.views import (
    appointments,
    consulta,
    home,
    new_schedule_appointment,
    schedule_appointment,
)

app_name = "patients"

urlpatterns = [
    path("home/", home, name="home"),
    path(
        "schedule_appointment/<int:doctor_id>/",
        schedule_appointment,
        name="schedule_appointment",
    ),
    path(
        "schedule_appointment/new/<int:appointment_id>/",
        new_schedule_appointment,
        name="new_schedule_appointment",
    ),
    path(
        "schedule_appointment/",
        appointments,
        name="appointments",
    ),
    path(
        "consulta/<int:appointment_id>/",
        consulta,
        name="consulta",
    ),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("logout/", views.logout, name="logout"),
    path("login/", views.login, name="login"),
    path("create/", views.create, name="create"),
]

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>{% block 'title' %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    {% block 'head' %}{% endblock 'head' %}
  </head>
  <body>
    {% block 'body' %}{% endblock 'body' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-color-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"><img src="{% static 'geral/img/logo.png' %}" width="20%" alt="">&nbspHEALING</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Área do paciente
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'patients:home' %}">Home</a></li>
                  <li><a class="dropdown-item" href="{% url 'patients:appointments' %}">Minhas consultas</a></li>
                </ul>
            </li>

            {% if is_medico %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Área do médico
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'doctors:appointments' %}">Abrir horários</a></li>
                        <li><a class="dropdown-item" href="{% url 'doctors:appointments_all' %}">Suas consultas</a></li>
                    </ul>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'doctors:create' %}">Sou médico</a>
                </li>
            {% endif %}
        </ul>
        
      </div>
      <a class="navbar-brand" href="{% url 'users:logout' %}">
        <span class="navbar-text">
          Sair
        </span>
    </a>
      
    </div>
  </nav>